# This is a basic workflow to help you get started with Actions

name: English Paper CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: konn/texlive2020-slim

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            **/*.aux
            **/*.bbl
            **/*.blg
            **/*.bcf
            **/*.fls
            **/*.out
            **/*.fdb_latexmk
            **/*.run.xml
          # An explicit key for restoring and saving the cache
          key: english-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            english-${{github.ref}}-${{ runner.os }}-
            english-${{github.ref}}-
            english-master-

      # Runs a set of commands using the runners shell
      - name: Typeset English Paper
        uses: konn/smooth-paper/.github/actions/typeset-latex@master
        with:
          workdir: english-paper
          target: smooth-english-paper.tex

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: english-paper-pdf
          path: english-paper/smooth-english-paper.pdf
          if-no-files-found: error # optional, default is warn
          retention-days: 90
