# This is a basic workflow to help you get started with Actions

name: RIMS Kokyuroku

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on:  ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: tex-cache
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            rims/rims-smooth-paper.fdb_latexmk
            rims/.latex/

          # An explicit key for restoring and saving the cache
          key: rims-${{github.ref}}-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.sty', '**/*.fdb_latexmk', 'extract-generateds.lua') }}
          restore-keys: |
            rims-${{github.ref}}-${{ runner.os }}-
            rims-${{github.ref}}-
            rims-master-
      - name: Create .latex directory if missing
        if: steps.tex-cache.outputs.cache-hit != 'true'
        run: mkdir -p .latex
      - name: Restore latex files
        if: steps.tex-cache.outputs.cache-hit == 'true'
        run: |
          pushd rims
          if [ -n "$(find .latex/ -mindepth 1 -maxdepth 1)" ]; then
            cp -r .latex/* .
          else
            echo "No .latex/ directory found. skip"
          fi
          popd
      - name: Typeset it
        run: |
          pushd rims
          ls
          latexmk -pdflua main.tex
          popd
      
      - name: Store latex generated files
        run: |
          pushd rims
          ls
          for fdb in $(find rims -name "*.fdb_latexmk"); do
              for i in $(cat $fdb | texlua ${GITHUB_WORKSPACE}/ci-resources/extract-generateds.lua); do
                echo "cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i"
                cp $(dirname $fdb)/$i .latex/$(dirname $fdb)/$i
              done
          done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: RIMS Kokyuroku
          path: rims.pdf
          if-no-files-found: error # optional, default is warn
          retention-days: 90

  lint:
    runs-on: ubuntu-18.04
    container: docker://konn/texlive2020-slim:20201227.4
    
    needs:
    - build
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.7
      with:
        # Artifact name
        name: RIMS Kokyuroku
        # Destination path
        path: rims
    - name: Tell me your pages
      run: |
        PAGES=$(pdfinfo rims/rims-smooth-paper.pdf | grep "Pages:" | cut -d ':' -f2 | sed 's/[ \t]*//g')
        if [ ${PAGES} -lt 20 ]; then
          echo "OK: Current pages ${PAGES} satisfies range."
        else
          echo "NG: Current page count ${PAGES} exeeds range!"
          exit 1
        fi
